version: '3.5'

services:
  postgres:
    container_name: postgres_database
    image: postgres:11.1-alpine
    volumes:
    - ./data/postgresql:/var/lib/postgresql/data
    restart: always
    env_file:
    - .env
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secretsecretsecret}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    depends_on:
      - postgres_database
    restart: unless-stopped

networks:
  postgres:
    external:
      name: livingmobile-networks
